### ISSUE TITLE
test_latents_seed100.pt

### ISSUE THREAD

**Issue by MengZhen-Chi** [hwang1996/ManiCLIP#1]
could you tell me how to get the "test_latents_seed100.pt" under the data direction, through e4e encoder?

**Comment by douxWh** [comment]
> could you tell me how to get the "test_latents_seed100.pt" under the data direction, through e4e encoder?
Excuse me, have you got the answer?

**Comment by MengZhen-Chi** [comment]
> > could you tell me how to get the "test_latents_seed100.pt" under the data direction, through e4e encoder?
> > Excuse me, have you got the answer?

nothing😂

**Comment by hwang1996** [comment]
We did not use the inverted real images for evaluation. 

The latents are randomly initialized nosie. They are used as the GAN generator's input to produce the original images. We set the ramdom seed as 100. Then we used the first sentences of the last 5,000 text files from Multi-Modal-CelebA-HQ dataset as the guidance to edit the original images for evaluation. 

Thanks.

**Comment by yuelang222** [comment]
Thanks to open source, how it works on the celebA-HQ 1024 dataset
